#!/bin/bash
# =============================================================================
# server/setup.sh — WireGuard Server Setup
# =============================================================================
# What this script does:
#   Sets up a WireGuard VPN server on a Linux VPS (Ubuntu 20.04/22.04).
#   Designed for Oracle Cloud Free Tier but works on any Ubuntu VPS.
#
# What it installs/configures:
#   - wireguard + wireguard-tools (via apt)
#   - Server key pair (private key stays on server, never leaves)
#   - /etc/wireguard/wg0.conf (server config)
#   - IP forwarding (lets server route traffic for VPN clients)
#   - iptables NAT rules (routes client traffic to the internet)
#   - wg-quick@wg0 systemd service (auto-starts on reboot)
#
# What the user needs to provide:
#   - Their Mac client public key (generated by install.sh on Mac)
#
# What the user gets at the end:
#   - Server public key (needed for Mac install.sh)
#   - Server IP (already know this — they SSH'd in)
#
# Requirements:
#   - Ubuntu 20.04 or 22.04
#   - Root or sudo access
#   - Port 51820 UDP open in your cloud firewall (Oracle security list)
#
# Usage:
#   bash setup.sh
#   or:
#   curl -fsSL https://raw.githubusercontent.com/codereyinish/wg-hotspot-mac/main/server/setup.sh | bash
#
# Author: github.com/codereyinish
# =============================================================================

set -e  # exit immediately if any command fails

# =============================================================================
# COLORS
# =============================================================================
RED=$'\033[91m'
GRN=$'\033[92m'
YLW=$'\033[93m'
BLU=$'\033[96m'
BLD=$'\033[1m'
RST=$'\033[0m'

# =============================================================================
# HELPERS
# =============================================================================

header() {
    echo ""
    echo "${BLD}${BLU}── $1 ${RST}"
}

ok() {
    echo "  ${GRN}✓${RST} $1"
}

info() {
    echo "  ${YLW}→${RST} $1"
}

die() {
    echo ""
    echo "  ${RED}✗ Error: $1${RST}"
    echo ""
    exit 1
}

ask() {
    local var=$1
    local question=$2
    local default=$3
    echo ""
    if [ -n "$default" ]; then
        printf "  ${BLD}$question${RST} [${default}]: "
    else
        printf "  ${BLD}$question${RST}: "
    fi
    read -r input
    if [ -z "$input" ] && [ -n "$default" ]; then
        eval "$var=\"$default\""
    else
        eval "$var=\"$input\""
    fi
}

# =============================================================================
# STEP 0 — Welcome
# =============================================================================
clear
echo ""
echo "${BLD}  WireGuard Hotspot Mac — Server Setup${RST}"
echo "  ────────────────────────────────────────"
echo "  Sets up your WireGuard VPN server."
echo "  Run this on your Oracle Cloud VPS (or any Ubuntu server)."
echo ""
echo "  You will need:"
echo "    • Your Mac client public key (from install.sh on your Mac)"
echo ""
read -rp "  Press Enter to start..."

# =============================================================================
# STEP 1 — Check this is Linux and running as root
# =============================================================================
header "Step 1/10 — Checking system"

if [ "$(uname)" != "Linux" ]; then
    die "This script must run on Linux (Ubuntu). Run it on your VPS, not your Mac."
fi
ok "Linux detected"

# Check running as root — required for apt, wg, systemctl
if [ "$EUID" -ne 0 ]; then
    die "Please run as root: sudo bash setup.sh"
fi
ok "Running as root"

# Detect Ubuntu version
if ! command -v apt &>/dev/null; then
    die "This script requires apt (Ubuntu/Debian). Other distros not supported yet."
fi

UBUNTU_VERSION=$(lsb_release -rs 2>/dev/null || echo "unknown")
ok "Ubuntu $UBUNTU_VERSION detected"

# =============================================================================
# STEP 2 — Update packages and install WireGuard
# =============================================================================
header "Step 2/10 — Installing WireGuard"

info "Updating package list..."
apt update -qq

info "Installing wireguard..."
apt install -y wireguard wireguard-tools iptables

ok "WireGuard installed"

# =============================================================================
# STEP 3 — Generate server key pair
# =============================================================================
header "Step 3/10 — Generating server keys"

# Generate server private key — stays on this server, never shared
# Public key is derived from it and given to the Mac client
SERVER_PRIVATE_KEY=$(wg genkey)
SERVER_PUBLIC_KEY=$(echo "$SERVER_PRIVATE_KEY" | wg pubkey)

ok "Server key pair generated"
info "Private key stays on this server — never share it"

# =============================================================================
# STEP 4 — Detect network interface
# =============================================================================
header "Step 4/10 — Detecting network interface"

# Auto-detect the main outbound network interface
# On Oracle Cloud this is usually ens3 or enp0s3 (not eth0)
# This is needed for iptables NAT rules — routes VPN traffic to internet
NET_IF=$(ip route | grep '^default' | awk '{print $5}' | head -1)

if [ -z "$NET_IF" ]; then
    die "Could not detect network interface. Check: ip route"
fi

ok "Network interface: $NET_IF"

# =============================================================================
# STEP 5 — Enable IP forwarding
# =============================================================================
header "Step 5/10 — Enabling IP forwarding"

# IP forwarding allows the server to route packets from VPN clients
# to the internet — without this, clients can connect but can't browse
echo "net.ipv4.ip_forward=1"            >> /etc/sysctl.conf
echo "net.ipv6.conf.all.forwarding=1"   >> /etc/sysctl.conf
sysctl -p &>/dev/null

ok "IPv4 and IPv6 forwarding enabled"

# =============================================================================
# STEP 6 — Collect config from user
# =============================================================================
header "Step 6/10 — Server configuration"

ask LISTEN_PORT   "WireGuard listen port"         "51820"
ask SERVER_ADDR   "Server VPN address"            "10.0.0.1"
ask CLIENT_ADDR   "Client VPN address (your Mac)" "10.0.0.2"

echo ""
echo "  ${BLD}Paste your Mac client public key below.${RST}"
echo "  (Generated by install.sh on your Mac — Step 5)"
ask CLIENT_PUBKEY "Client public key" ""

[ -z "$CLIENT_PUBKEY" ] && die "Client public key cannot be empty"

# =============================================================================
# STEP 7 — Create /etc/wireguard/wg0.conf
# =============================================================================
header "Step 7/10 — Creating server config"

# PostUp/PostDown: iptables NAT rules
#   MASQUERADE — rewrites source IP of VPN packets to server's IP
#   so the internet sees your server's IP, not the VPN client's internal IP
#   FORWARD — allows packets to pass between wg0 and the internet interface
#   NOTE: use -I FORWARD 1 (insert at top), NOT -A (append). Oracle's Ubuntu
#   image ships a default "FORWARD ... REJECT" rule; appending puts our ACCEPT
#   below it, so it never matches and clients get no internet. Inserting at
#   position 1 puts ACCEPT before the REJECT.
cat > /etc/wireguard/wg0.conf << EOF
[Interface]
PrivateKey = ${SERVER_PRIVATE_KEY}
Address = ${SERVER_ADDR}/24
ListenPort = ${LISTEN_PORT}
PostUp   = iptables -I FORWARD 1 -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o ${NET_IF} -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o ${NET_IF} -j MASQUERADE

# Mac client
[Peer]
PublicKey  = ${CLIENT_PUBKEY}
AllowedIPs = ${CLIENT_ADDR}/32
EOF

chmod 600 /etc/wireguard/wg0.conf
ok "Server config created at /etc/wireguard/wg0.conf"

# =============================================================================
# STEP 8 — Enable and start WireGuard
# =============================================================================
header "Step 8/10 — Starting WireGuard"

# Enable: auto-starts on every reboot
# Start: brings the tunnel up right now
systemctl enable wg-quick@wg0
systemctl start  wg-quick@wg0

ok "WireGuard service started"
ok "Auto-starts on reboot"

# Verify it's running
if systemctl is-active --quiet wg-quick@wg0; then
    ok "WireGuard is running ✓"
else
    die "WireGuard failed to start. Check: journalctl -u wg-quick@wg0"
fi

# =============================================================================
# STEP 9 — Open firewall (if ufw is active)
# =============================================================================
header "Step 9/10 — Firewall"

if command -v ufw &>/dev/null && ufw status | grep -q "Status: active"; then
    ufw allow "$LISTEN_PORT"/udp
    ok "ufw: port $LISTEN_PORT UDP opened"
else
    info "ufw not active — skipping"
fi

# Oracle Cloud / AWS users: you MUST also open the port in your
# cloud provider's security list/security group (web console)
# Oracle: Networking → VCN → Security Lists → Add Ingress Rule
#   Protocol: UDP, Port: 51820
echo ""
echo "  ${YLW}⚠️  Cloud firewall reminder:${RST}"
echo "  If you're on Oracle Cloud, you must also open UDP $LISTEN_PORT"
echo "  in the Oracle web console:"
echo "  Networking → VCN → Security Lists → Add Ingress Rule"
echo "  Protocol: UDP  |  Port: $LISTEN_PORT"

# =============================================================================
# STEP 10 — Done — show server public key
# =============================================================================
header "Step 10/10 — Setup complete"

echo ""
echo "${GRN}${BLD}  ✓ Server setup complete!${RST}"
echo ""
echo "  ┌─────────────────────────────────────────────┐"
echo "  │  Your server public key (copy this):        │"
echo "  │                                             │"
echo "  │  ${BLU}${SERVER_PUBLIC_KEY}${RST}"
echo "  │                                             │"
echo "  │  You'll need this when running install.sh   │"
echo "  │  on your Mac.                               │"
echo "  └─────────────────────────────────────────────┘"
echo ""
echo "  Server details for your Mac install:"
echo "  ${YLW}  Server IP:   $(curl -s ifconfig.me 2>/dev/null || echo 'check your VPS IP')${RST}"
echo "  ${YLW}  Server port: $LISTEN_PORT${RST}"
echo "  ${YLW}  Public key:  $SERVER_PUBLIC_KEY${RST}"
echo ""
echo "  Now run install.sh on your Mac."
echo ""
